services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"

  - type: static_site
    name: project
    buildCommand: "cd frontend && npm install && npm run build"
    publishDir: "frontend/dist"
