services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"

  - type: web
    name: project
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
